### ISSUE TITLE
Diferencias Absolutas en expect_equal

### ISSUE THREAD

**Issue by harobledo** [harobledo/fixest#1]
@pachadotdev, 

Uno de los errores que aparecieron en mi código (y que corregí) es que el autor originalmente hace comparaciones absolutas y no relativas entre las estimaciones de lm-felm, glm-feglm y glm.nb-fenegbin. Estuve averiguando cómo forzar a testtat::expect_equal a que hiciera comparaciones absolutas, y una opción era utilizar una edición anterior de expect_equal (local_edition(2) ) que permitía el argumento scale = 1 para hacer comparaciones absolutas. 

https://github.com/harobledo/fixest/blob/master/tests/testthat/helper-expectation.R#L6-L10

Sigo averiguando cómo hacer la comparación absoluta sin cambiar de edición

**Comment by pachadotdev** [comment]
voy a preguntar en rOpenSci, así que acá lo traduzco:

One of the bugs that appeared in my code (and which I corrected) is that the author originally makes absolute and not relative comparisons between lm-felm, glm-feglm and glm.nb-fenegbin estimates. I was figuring out how to force testtat::expect_equal to make absolute comparisons, and one option was to use an earlier edition of expect_equal (local_edition(2) ) that allowed the scale = 1 argument to make absolute comparisons.

https://github.com/harobledo/fixest/blob/master/tests/testthat/helper-expectation.R#L6-L10

I'm still figuring out how to do the absolute comparison without changing editions.

Translated with www.DeepL.com/Translator (free version)

**Comment by pachadotdev** [comment]
@harobledo, @karawoo sent me this on rOpenSci's chat:

> I don’t know if there are built-in ways to do this with 3e but probably you could do it with a custom expectation https://testthat.r-lib.org/articles/custom-expectation.html
> testthat.r-lib.orgtestthat.r-lib.org

**Comment by harobledo** [comment]
Thanks @pachadotdev and @karawoo for the answer. In the end, i created a wrapper for expect_equal which considers its second edition, which again is a wrapper of R's all.equal function. The former has a scale argument that allows for testing for absolute differences

https://github.com/harobledo/fixest/blob/master/tests/testthat/helper-expectation.R#L3-L6
