### ISSUE TITLE
Warning: test_that code must be a braced expression

### ISSUE THREAD

**Issue by harobledo** [harobledo/fixest#2]
@pachadotdev

Todos los patrick::with_parameters_test_that que uso arrojan: "The `code` argument to `test_that()` must be a braced expression to get accurate file-line information for failures."
https://github.com/harobledo/fixest/blob/master/tests/testthat/test-fitting.R#L5-L14

El warning sería que no incluí {} en el segundo argumento de alguno de los test_that, pero yo veo que está incluido en todos, por ejemplo, en la función expect_ols_equal de helper-expectation.R:
https://github.com/harobledo/fixest/blob/master/tests/testthat/helper-expectation.R#L4-L33

**Comment by pachadotdev** [comment]
hola @harobledo 
eso me pasó con el eflm! lo que hice en su momento fue sacar la versión de testthat de DESCRIPTION para poner la vara más baja, voy a consultar en rOpenSci pq aún estoy en R 3.6 y testthat 2.0
