### ISSUE TITLE
Errores en test-sandwich.R

### ISSUE THREAD

**Issue by harobledo** [harobledo/fixest#7]
@pachadotdev

Estoy teniendo un error que pareciera provenir más bien del paquete sandwich, ya que al ajustar una regresión lineal con efectos fijos con lm() parece que vcovCL no está encontrando dentro del modelo los objetos asociados a la estimación de la variable "x". 

https://github.com/harobledo/fixest/blob/master/tests/testthat/test-sandwich.R#L39-L43

Antes no ocurría esto, y no estoy entendiendo del todo por qué ahora sí está ocurriendo.

**Comment by pachadotdev** [comment]
es un cambio en el pkg sandwich, lo arreglé anoche :)
